//------------CUSTOMER---------------------
export const FIND_ALL_CUSTOMER = "FIND_ALL_CUSTOMER"
export const FIND_ALL_CUSTOMER_SUCCESS = "FIND_ALL_CUSTOMER_SUCCESS"
export const FIND_ALL_CUSTOMER_FAILURE = "FIND_ALL_CUSTOMER_FAILURE"

export const SAVE_CUSTOMER = "SAVE_CUSTOMER"
export const SAVE_CUSTOMER_SUCCESS = "SAVE_CUSTOMER_SUCCESS"
export const SAVE_CUSTOMER_FAILURE = "SAVE_CUSTOMER_FAILURE"

export const FIND_CUSTOMER_BY_ID = "FIND_CUSTOMER_BY_ID"
export const FIND_CUSTOMER_BY_ID_SUCCESS = "FIND_CUSTOMER_BY_ID_SUCCESS"
export const FIND_CUSTOMER_BY_ID_FAILURE = "FIND_CUSTOMER_BY_ID_FAILURE"

export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER"
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS"
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE"

//----------------------FIND CUSTOMER BY STAFF---------------------------
export const FIND_CUSTOMER_BY_SUBMITTER = "FIND_CUSTOMER_BY_SUBMITTER"
export const FIND_CUSTOMER_BY_SUBMITTER_SUCCESS = "FIND_CUSTOMER_BY_SUBMITTER_SUCCESS"
export const FIND_CUSTOMER_BY_SUBMITTER_FAILURE = "FIND_CUSTOMER_BY_SUBMITTER_FAILURE"

//------------TRANSACTION-------------------

export const FIND_ALL_TRANSACTION = "FIND_ALL_TRANSACTION"
export const FIND_ALL_TRANSACTION_SUCCESS = "FIND_ALL_TRANSACTION_SUCCESS"
export const FIND_ALL_TRANSACTION_FAILURE = "FIND_ALL_TRANSACTION_FAILURE"

export const SAVE_TRANSACTION = "SAVE_TRANSACTION"
export const SAVE_TRANSACTION_SUCCESS = "SAVE_TRANSACTION_SUCCESS"
export const SAVE_TRANSACTION_FAILURE = "SAVE_TRANSACTION_FAILURE"

export const FIND_TRANSACTION_BY_ID = "FIND_TRANSACTION_BY_ID"
export const FIND_TRANSACTION_BY_ID_SUCCESS = "FIND_TRANSACTION_BY_ID_SUCCESS"
export const FIND_TRANSACTION_BY_ID_FAILURE = "FIND_TRANSACTION_BY_ID_FAILURE"

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION"
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS"
export const UPDATE_TRANSACTION_FAILURE = "UPDATE_TRANSACTION_FAILURE"

//-------------TRANSACTION BY STAFF--------------------------------------
export const FIND_TRANSACTION_BY_STAFF = "FIND_TRANSACTION_BY_STAFF"
export const FIND_TRANSACTION_BY_STAFF_SUCCESS = "FIND_TRANSACTION_BY_STAFF_SUCCESS"
export const FIND_TRANSACTION_BY_STAFF_FAILURE = "FIND_TRANSACTION_BY_STAFF_FAILURE"

// ------------------LOGIN------------------------------------

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

//-----------------------CREATE ACCOUNT--------------------------------

export const FIND_ALL_ACCOUNT = "FIND_ALL_ACCOUNT"
export const FIND_ALL_ACCOUNT_SUCCESS = "FIND_ALL_ACCOUNT_SUCCESS"
export const FIND_ALL_ACCOUNT_FAILURE = "FIND_ALL_ACCOUNT_FAILURE"

export const SAVE_ACCOUNT = "SAVE_ACCOUNT"
export const SAVE_ACCOUNT_SUCCESS = "SAVE_ACCOUNT_SUCCESS"
export const SAVE_ACCOUNT_FAILURE = "SAVE_ACCOUNT_FAILURE"

export const FIND_ACCOUNT_BY_ID = "FIND_ACCOUNT_BY_ID"
export const FIND_ACCOUNT_BY_ID_SUCCESS = "FIND_ACCOUNT_BY_ID_SUCCESS"
export const FIND_ACCOUNT_BY_ID_FAILURE = "FIND_ACCOUNT_BY_ID_FAILURE"

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS"
export const UPDATE_ACCOUNT_FAILURE = "UPDATE_ACCOUNT_FAILURE"

export const REMOVE_ACCOUNT_BY_ID = "REMOVE_ACCOUNT_BY_ID"
export const REMOVE_ACCOUNT_BY_ID_SUCCESS = "REMOVE_ACCOUNT_BY_ID_SUCCESS"
export const REMOVE_ACCOUNT_BY_ID_FAILURE = "REMOVE_ACCOUNT_BY_ID_FAILURE"

//---------------------REPORT------------------------------------------
export const FIND_ALL_REPORT = "FIND_ALL_REPORT"
export const FIND_ALL_REPORT_SUCCESS = "FIND_ALL_REPORT_SUCCESS"
export const FIND_ALL_REPORT_FAILURE = " FIND_ALL_REPORT_FAILURE"

//--------------------REPORT BY STAFF--------------------------------
export const FIND_REPORT_BY_STAFF = "FIND_REPORT_BY_STAFF"
export const FIND_REPORT_BY_STAFF_SUCCESS = "FIND_REPORT_BY_STAFF_SUCCESS"
export const FIND_REPORT_BY_STAFF_FAILURE = "FIND_REPORT_BY_STAFF_FAILURE"

//----------------------APPROVAL----------------------------------------
export const SAVE_APPROVAL = "SAVE_APPROVAL"
export const SAVE_APPROVAL_SUCCESS = "SAVE_APPROVAL_SUCCESS"
export const SAVE_APPROVAL_FAILURE = "SAVE_APPROVAL_FAILURE"

export const FIND_APPROVAL_BY_ID = "FIND_APPROVAL_BY_ID"
export const FIND_APPROVAL_BY_ID_SUCCESS = "FIND_APPROVAL_BY_ID_SUCCESS"
export const FIND_APPROVAL_BY_ID_FAILURE = "FIND_APPROVAL_BY_ID_FAILURE"

export const FIND_ALL_APPROVAL = "FIND_ALL_APPROVAL"
export const FIND_ALL_APPROVAL_SUCCESS = "FIND_ALL_APPROVAL_SUCCESS"
export const FIND_ALL_APPROVAL_FAILURE = "FIND_ALL_APPROVAL_FAILURE"

export const FIND_APPROVAL_SUBMITTER_BY_ID = "FIND_APPROVAL_SUBMITTER_BY_ID"
export const FIND_APPROVAL_SUBMITTER_BY_ID_SUCCESS = "FIND_APPROVAL_SUBMITTER_BY_ID_SUCCESS"
export const FIND_APPROVAL_SUBMITTER_BY_ID_FAILURE = "FIND_APPROVAL_SUBMITTER_BY_ID_FAILURE"

//------------------------NEEDTYPE----------------------------
export const SAVE_NEEDTYPE = "SAVE_NEEDTYPE"
export const SAVE_NEEDTYPE_SUCCESS = "SAVE_NEEDTYPE_SUCCESS"
export const SAVE_NEEDTYPE_FAILURE = "SAVE_NEEDTYPE_FAILURE"

export const FIND_ALL_NEEDTYPE = "FIND_ALL_NEEDTYPE"
export const FIND_ALL_NEEDTYPE_SUCCESS = "FIND_ALL_NEEDTYPE_SUCCESS"
export const FIND_ALL_NEEDTYPE_FAILURE = " FIND_ALL_NEEDTYPE_FAILURE"

export const FIND_NEEDTYPE_BY_ID = "FIND_NEEDTYPE_BY_ID"
export const FIND_NEEDTYPE_BY_ID_SUCCESS = "FIND_NEEDTYPE_BY_ID_SUCCESS"
export const FIND_NEEDTYPE_BY_ID_FAILURE = "FIND_NEEDTYPE_BY_ID_FAILURE"

export const REMOVE_NEEDTYPE_BY_ID = "REMOVE_NEEDTYPE_BY_ID"
export const REMOVE_NEEDTYPE_BY_ID_SUCCESS = "REMOVE_NEEDTYPE_BY_ID_SUCCESS"
export const REMOVE_NEEDTYPE_BY_ID_FAILURE = "REMOVE_NEEDTYPE_BY_ID_FAILURE"

export const UPDATE_NEEDTYPE = "UPDATE_NEEDTYPE"
export const UPDATE_NEEDTYPE_SUCCESS = "UPDATE_NEEDTYPE_SUCCESS"
export const UPDATE_NEEDTYPE_FAILURE = "UPDATE_NEEDTYPE_FAILURE"

//----------------------------ROLE--------------------------------------------
export const FIND_ALL_ROLE = "FIND_ALL_ROLE"
export const FIND_ALL_ROLE_SUCCESS = "FIND_ALL_ROLE_SUCCESS"
export const FIND_ALL_ROLE_FAILURE = "FIND_ALL_ROLE_FAILURE"

export const SAVE_ROLE = "SAVE_ROLE"
export const SAVE_ROLE_SUCCESS = "SAVE_ROLE_SUCCESS"
export const SAVE_ROLE_FAILURE = "SAVE_ROLE_FAILURE"

export const FIND_ROLE_BY_ID = "FIND_ROLE_BY_ID"
export const FIND_ROLE_BY_ID_SUCCESS = "FIND_ROLE_BY_ID_SUCCESS"
export const FIND_ROLE_BY_ID_FAILURE = "FIND_ROLE_BY_ID_FAILURE"

export const REMOVE_ROLE_BY_ID = "REMOVE_ROLE_BY_ID"
export const REMOVE_ROLE_BY_ID_SUCCESS = "REMOVE_ROLE_BY_ID_SUCCESS"
export const REMOVE_ROLE_BY_ID_FAILURE = "REMOVE_ROLE_BY_ID_FAILURE"

export const UPDATE_ROLE_BY_ID = "UPDATE_ROLE_BY_ID"
export const UPDATE_ROLE_BY_ID_SUCCESS = "UPDATE_ROLE_BY_ID_SUCCESS"
export const UPDATE_ROLE_BY_ID_FAILURE = "UPDATE_ROLE_BY_ID_FAILURE"

//------------------------USER--------------------------------------------
export const CHANGE_PASSWORD_USER = "CHANGE_PASSWORD_USER"
export const CHANGE_PASSWORD_USER_SUCCESS = "CHANGE_PASSWORD_USER_SUCCESS"
export const CHANGE_PASSWORD_USER_FAILURE = "CHANGE_PASSWORD_USER_FAILURE"

export const SAVE_PASSWORD = "SAVE_PASSWORD"
export const SAVE_PASSWORD_SUCCESS = "SAVE_PASSWORD_SUCCESS"
export const SAVE_PASSWORD_FAILURE = "SAVE_PASSWORD_FAILURE"

//------------------------DASHBOARD-----------------------------------
export const FIND_TOTAL = "FIND_TOTAL"
export const FIND_TOTAL_SUCCESS = "FIND_TOTAL_SUCCESS"
export const FIND_TOTAL_FAILURE = "FIND_TOTAL_FAILURE"

//-------------------------FILTER--------------------------------
export const FIND_REPORT_BY_APPROVED = "FIND_REPORT_BY_APPROVED"
export const FIND_REPORT_BY_APPROVED_SUCCESS = "FIND_REPORT_BY_APPROVED_SUCCESS"
export const FIND_REPORT_BY_APPROVED_FAILURE = "FIND_REPORT_BY_APPROVED_FAILURE"

export const FIND_REPORT_BY_REJECTED = "FIND_REPORT_BY_REJECTED"
export const FIND_REPORT_BY_REJECTED_SUCCESS = "FIND_REPORT_BY_REJECTED_SUCCESS"
export const FIND_REPORT_BY_REJECTED_FAILURE = "FIND_REPORT_BY_REJECTED_FAILURE"
